site_name: game-dev-self-learning
site_url: http://game-dev-self-learning
site_author: Max1122Chen

repo_name: game-dev-self-learning
repo_url: https://github.com/Max1122Chen/game-dev-self-learning/

theme:
  name: material
  language: zh
  static_templates:
    - 404.html

  features:
    - header.autohide
    
nav:
  - 欢迎: "index.md"
  - 怎样从这里开始学习？: "怎样从这里开始学习？.md"
  - 游戏设计理论: 
  - 游戏开发中的计算机科学: 
    - 计算机科学基础学习指路——《CS自学指南》: "计算机科学基础学习指路——《CS自学指南》.md"
  - 游戏开发中的美术: 
  - 游戏开发中的音乐: 
  - 游戏开发中的文学: 
  - 游戏引擎使用:
    - Unity:
    - Unreal Engine:
    - Godot:

plugins:
  - search

watch: 
  - ./