site_name: game-dev-self-learning
site_url: http://www.game-dev-self-learning.wiki
site_author: Max1122Chen

repo_name: game-dev-self-learning
repo_url: https://github.com/Max1122Chen/game-dev-self-learning/

theme:
  name: material
  language: zh
  static_templates:
    - 404.html

  features:
    - header.autohide
    - navigation.instant

  palette:
    primary: orange

    
nav:
    - 欢迎: "index.md"
    - 怎样从这里开始学习？: "怎样从这里开始学习？.md"
    - 各种各样的学习建议:
      - "各种各样的学习建议/MaxChen's游戏开发技能树加点推荐.md"
    - 基础工具: "placeholder.md"
    - 游戏设计理论: 
      - 《游戏设计艺术》: "游戏设计理论/《游戏设计艺术》.md" 
    - 游戏开发中的数学: "游戏开发中的数学/placeholder.md"
    - 游戏开发中的计算机科学: 
      - 计算机科学基础学习指路——《CS自学指南》: "游戏开发中的计算机科学/计算机科学基础学习指路——《CS自学指南》.md"
      - 高级语言基础: "placeholder.md"
      - 设计模式: "placeholder.md"
      - 计算机图形学: 
        - GAMES101-现代计算机图形学入门: "游戏开发中的计算机科学/计算机图形学/GAMES101-现代计算机图形学入门-"
    - 游戏开发中的美术: "游戏开发中的美术/placeholder.md"
    - 游戏开发中的音乐: "游戏开发中的音乐/placeholder.md"
    - 游戏开发中的文学: "游戏开发中的文学/placeholder.md"
    - 游戏引擎:
      - 游戏引擎架构: 
        - GAMES104-现代游戏引擎：从入门到实践: "游戏引擎/游戏引擎架构/GAMES104-现代游戏引擎：从入门到实践.md"
      - Unity: "游戏引擎/Unity/placeholder.md"
      - Unreal Engine: 
        - 虚幻引擎官方文档: "游戏引擎/Unreal Engine/虚幻引擎官方文档.md"
        - 虚幻引擎入门: 
          - Unreal Engine 5 C++ Game Development: "游戏引擎/Unreal Engine/虚幻引擎入门/Unreal Engine 5 C++ Game Development.md"
          - 【虚幻4】UE4初学者系列教程合集-全中文新手入门教程: "游戏引擎/Unreal Engine/虚幻引擎入门/【虚幻4】UE4初学者系列教程合集-全中文新手入门教程.md"
        - 虚幻引擎进阶:
          - 虚幻Gameplay架构:
            - 《InsideUE4》GamePlay架构: "游戏引擎/Unreal Engine/虚幻引擎进阶/虚幻Gameplay架构/《InsideUE4》GamePlay架构.md"
          - GameplayAbilitySystem: "placeholder.md"
      - Godot: "游戏引擎/Godot/placeholder.md"
    - 给贡献者: 
      - 贡献资源的注意事项: "给贡献者/贡献资源的注意事项.md"
      - 知识推荐模板: "给贡献者/知识推荐模板.md"
      - 文章编写模板: "placeholder.md"
    

extra:
  disqus: <shortname>

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

watch: 
  - ./